# Generated by Django 4.0 on 2021-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
