# Generated by Django 4.0 on 2021-12-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='extension',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
