# Generated by Django 4.0 on 2021-12-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0006_alter_contact_extension_alter_contact_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('expiriration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_addedby', to='tabicrm.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_customer', to='tabicrm.customer')),
            ],
        ),
    ]
