# Generated by Django 4.0 on 2021-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0007_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='type',
        ),
        migrations.RemoveField(
            model_name='license',
            name='vendor',
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.CharField(choices=[('AVAST PRO', 'AVAST PRO'), ('AVAST ENDPOINT', 'AVAST ENDPOINT'), ('MALWAREBYTES', 'MALWAREBYTES'), ('MICROSOFT OFFICE 2010', 'MICROSOFT OFFICE 2010'), ('MICROSOFT OFFICE 2013', 'MICROSOFT OFFICE 2013'), ('MICROSOFT OFFICE 2016', 'MICROSOFT OFFICE 2016'), ('MICROSOFT OFFICE 2019', 'MICROSOFT OFFICE 2019'), ('MICROSOFT OFFICE 365', 'MICROSOFT OFFICE 365')], default='AVAST PRO', max_length=255),
        ),
    ]
