# Generated by Django 4.0 on 2021-12-21 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0011_alter_license_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/%m_%d_%Y'),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
