# Generated by Django 4.0 on 2021-12-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0012_alter_license_license_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_file',
            field=models.FileField(blank=True, default=None, upload_to='licenses/%m_%d_%Y'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SERVER', 'SERVER'), ('UPS', 'UPS'), ('ROUTER', 'ROUTER'), ('SWITCH', 'SWITCH'), ('MODEM', 'MODEM'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('PRINTER', 'PRINTER'), ('IP_PHONE', 'IP_PHONE'), ('TABLET', 'TABLET'), ('CELL_PHONE', 'CELL_PHONE'), ('OTHER', 'OTHER')], default='SERVER', max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('internal_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('external_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ilo_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('subnet_mask', models.CharField(blank=True, max_length=255, null=True)),
                ('default_gateway', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_one', models.CharField(blank=True, max_length=255, null=True)),
                ('dns_two', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_equipment', to='tabicrm.customer')),
            ],
        ),
    ]
