# Generated by Django 4.0 on 2021-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0013_alter_license_license_file_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='end_of_life',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
