# Generated by Django 4.0 on 2021-12-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0015_alter_equipment_end_of_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_addedby', to='tabicrm.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addedby', to='tabicrm.user'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_addedby', to='tabicrm.user'),
        ),
    ]
