# Generated by Django 4.0 on 2021-12-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0018_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='assigned_to',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ilo_ip_address',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('ILO', 'ILO (or equivelent)'), ('UPS', 'UPS'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('WAP', 'Wireless Access Point'), ('MODEM', 'Modem'), ('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('PRINTER', 'Printer'), ('IP_PHONE', 'IP Phone'), ('RECEIPTER', 'Receipter'), ('PRINT_SERVER', 'Print Server'), ('TABLET', 'Tablet'), ('CELL_PHONE', 'Cell phone'), ('OTHER', 'Other')], default='SERVER', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='results',
            field=models.CharField(choices=[('SOLVED_ON_PHONE', 'Solved on phone'), ('SERVER_SERVICE', 'Server service'), ('ROUTER_SERVICE', 'Router service'), ('CONTRACT_SERVICE', 'Contract service'), ('NON_CONTRACT_SERVICE', 'Non-contract service')], default='SOLVED_ON_PHONE', max_length=255),
        ),
    ]
