# Generated by Django 4.0 on 2021-12-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0019_rename_assigned_to_contact_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Server', 'Server'), ('ILO', 'ILO (or equivalent)'), ('UPS', 'UPS'), ('Router', 'Router'), ('Switch', 'Switch'), ('WAP', 'Wireless Access Point'), ('Modem', 'Modem'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('IP Phone', 'IP Phone'), ('Receipter', 'Receipter'), ('Print Server', 'Print Server'), ('Tablet', 'Tablet'), ('Cell Phont', 'Cell phone'), ('Other', 'Other')], default='Server', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='product',
            field=models.CharField(choices=[('Avast Pro', 'Avast Pro'), ('Avast Endpoint Protection', 'Avast Endpoint Protection'), ('Malwarebytes', 'Malwarebytes'), ('Microsoft Office 2010', 'Microsoft Office 2010'), ('Microsoft Office 2013', 'Microsoft Office 2013'), ('Microsoft Office 2016', 'Microsoft Office 2016'), ('Microsoft Office 2019', 'Microsoft Office 2019'), ('Microsoft Office 365', 'Microsoft Office 365')], default='Avast Pro', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'LOW'), ('Normal', 'NORMAL'), ('High', 'HIGH'), ('Urgent', 'URGENT')], default='Normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='results',
            field=models.CharField(choices=[('Solved on Phone', 'Solved on phone'), ('Server service', 'Server service'), ('Router service', 'Router service'), ('Contract service', 'Contract service'), ('Non-contract service', 'Non-contract service')], default='Solved on Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('In Progres', 'IN PROGRESS'), ('Waiting on customer', 'WAITING ON CUSTOMER'), ('Closed', 'CLOSED')], default='OPEN', max_length=255),
        ),
    ]
