# Generated by Django 4.0 on 2021-12-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0020_alter_equipment_type_alter_license_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='dns_one',
            new_name='primary_dns',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='dns_two',
            new_name='secondary_dns',
        ),
    ]
