# Generated by Django 4.0 on 2021-12-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0022_ticket_owned_by_alter_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
