# Generated by Django 4.0 on 2021-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabicrm', '0023_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('SERVER', 'SERVER'), ('ILO', 'ILO'), ('UPS', 'UPS'), ('ROUTER', 'ROUTER'), ('SWITCH', 'SWITCH'), ('WAP', 'WAP'), ('MODEM', 'MODEM'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('PRINTER', 'PRINTER'), ('IP_PHONE', 'IP_PHONE'), ('RECEIPTER', 'RECEIPTER'), ('PRINT_SERVER', 'PRINT_SERVER'), ('TABLET', 'TABLET'), ('CELL_PHONE', 'CELL_PHONE'), ('OTHER', 'OTHER')], default='SERVER', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='product',
            field=models.CharField(choices=[('AVAST PRO', 'Avast Pro'), ('AVAST ENDPOINT PROTECTION', 'Avast Endpoint Protection'), ('MALWAREBYTES', 'Malwarebytes'), ('MICROSOFT OFFICE 2010', 'MICROSOFT OFFICE 2010'), ('MICROSOFT OFFICE 2013', 'MICROSOFT OFFICE 2013'), ('MICROSOFT OFFICE 2016', 'MICROSOFT OFFICE 2016'), ('MICROSOFT OFFICE 2019', 'MICROSOFT OFFICE 2019'), ('MICROSOFT OFFICE 365', 'MICROSOFT OFFICE 365')], default='AVAST PRO', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(choices=[('NETWORK', 'NETWORK SUPPORT'), ('SOFTWARE', 'SOFTWARE SUPPORT'), ('SERVER', 'SERVER SUPPORT'), ('HARDWARE', 'HARDWARE SUPPORT'), ('SALES', 'SALES'), ('DEVELOPMENT', 'DEVELOPMENT')], default='SOFTWARE', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('NORMAL', 'NORMAL'), ('HIGH', 'HIGH'), ('URGENT', 'URGENT')], default='NORMAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='results',
            field=models.CharField(choices=[('SOLVED ON PHONE', 'SOLVED ON PHONE'), ('SERVER SERVICE', 'SERVER SERVICE'), ('ROUTER SERVICE', 'ROUTER SERVICE'), ('CONTRACT SERVICE', 'CONTRACT SERVICE'), ('NON-CONTRACT SERVICE', 'NON-CONTRACT SERVICE')], default='SOLVED ON PHONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('WAITING ON CUSTOMER', 'WAITING ON CUSTOMER'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=255),
        ),
    ]
